// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: databasa.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric int32

const (
	Metric_COSINE      Metric = 0
	Metric_L2          Metric = 1
	Metric_DOT_PRODUCT Metric = 2
)

// Enum value maps for Metric.
var (
	Metric_name = map[int32]string{
		0: "COSINE",
		1: "L2",
		2: "DOT_PRODUCT",
	}
	Metric_value = map[string]int32{
		"COSINE":      0,
		"L2":          1,
		"DOT_PRODUCT": 2,
	}
)

func (x Metric) Enum() *Metric {
	p := new(Metric)
	*p = x
	return p
}

func (x Metric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric) Descriptor() protoreflect.EnumDescriptor {
	return file_databasa_proto_enumTypes[0].Descriptor()
}

func (Metric) Type() protoreflect.EnumType {
	return &file_databasa_proto_enumTypes[0]
}

func (x Metric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric.Descriptor instead.
func (Metric) EnumDescriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{0}
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     uint32                 `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric        Metric                 `protobuf:"varint,3,opt,name=metric,proto3,enum=databasa.Metric" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_databasa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetric() Metric {
	if x != nil {
		return x.Metric
	}
	return Metric_COSINE
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_databasa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{1}
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_databasa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_databasa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{3}
}

type CollectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     uint32                 `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric        Metric                 `protobuf:"varint,3,opt,name=metric,proto3,enum=databasa.Metric" json:"metric,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	HasIndex      bool                   `protobuf:"varint,5,opt,name=has_index,json=hasIndex,proto3" json:"has_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfo) Reset() {
	*x = CollectionInfo{}
	mi := &file_databasa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfo) ProtoMessage() {}

func (x *CollectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfo.ProtoReflect.Descriptor instead.
func (*CollectionInfo) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{4}
}

func (x *CollectionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionInfo) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CollectionInfo) GetMetric() Metric {
	if x != nil {
		return x.Metric
	}
	return Metric_COSINE
}

func (x *CollectionInfo) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CollectionInfo) GetHasIndex() bool {
	if x != nil {
		return x.HasIndex
	}
	return false
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_databasa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{5}
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionInfo      `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_databasa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{6}
}

func (x *ListCollectionsResponse) GetCollections() []*CollectionInfo {
	if x != nil {
		return x.Collections
	}
	return nil
}

type CreateIndexRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Collection     string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	M              uint32                 `protobuf:"varint,2,opt,name=m,proto3" json:"m,omitempty"`                                                 // max connections per node (default 16)
	EfConstruction uint32                 `protobuf:"varint,3,opt,name=ef_construction,json=efConstruction,proto3" json:"ef_construction,omitempty"` // build-time beam width (default 200)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_databasa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{7}
}

func (x *CreateIndexRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CreateIndexRequest) GetM() uint32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *CreateIndexRequest) GetEfConstruction() uint32 {
	if x != nil {
		return x.EfConstruction
	}
	return 0
}

type CreateIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexResponse) Reset() {
	*x = CreateIndexResponse{}
	mi := &file_databasa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexResponse) ProtoMessage() {}

func (x *CreateIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{8}
}

type DropIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropIndexRequest) Reset() {
	*x = DropIndexRequest{}
	mi := &file_databasa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropIndexRequest) ProtoMessage() {}

func (x *DropIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropIndexRequest.ProtoReflect.Descriptor instead.
func (*DropIndexRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{9}
}

func (x *DropIndexRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type DropIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropIndexResponse) Reset() {
	*x = DropIndexResponse{}
	mi := &file_databasa_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropIndexResponse) ProtoMessage() {}

func (x *DropIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropIndexResponse.ProtoReflect.Descriptor instead.
func (*DropIndexResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{10}
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_databasa_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{11}
}

func (x *InsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InsertRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_databasa_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{12}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_databasa_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{13}
}

func (x *GetRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_databasa_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{14}
}

func (x *GetResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_databasa_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_databasa_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{16}
}

type SearchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Collection       string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Embedding        []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	TopK             uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	EfSearch         uint32                 `protobuf:"varint,4,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`                         // search beam width (default 50, 0 = use default)
	IncludeEmbedding bool                   `protobuf:"varint,5,opt,name=include_embedding,json=includeEmbedding,proto3" json:"include_embedding,omitempty"` // when true, SearchResult may include full embedding payload
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_databasa_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{17}
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *SearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetEfSearch() uint32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *SearchRequest) GetIncludeEmbedding() bool {
	if x != nil {
		return x.IncludeEmbedding
	}
	return false
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`                // distance (lower = more similar for L2/cosine)
	Embedding     []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // optional payload; filled when requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_databasa_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{18}
}

func (x *SearchResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_databasa_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{19}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BatchInsertItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertItem) Reset() {
	*x = BatchInsertItem{}
	mi := &file_databasa_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertItem) ProtoMessage() {}

func (x *BatchInsertItem) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertItem.ProtoReflect.Descriptor instead.
func (*BatchInsertItem) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{20}
}

func (x *BatchInsertItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BatchInsertItem) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type BatchInsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Items         []*BatchInsertItem     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertRequest) Reset() {
	*x = BatchInsertRequest{}
	mi := &file_databasa_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertRequest) ProtoMessage() {}

func (x *BatchInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertRequest.ProtoReflect.Descriptor instead.
func (*BatchInsertRequest) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{21}
}

func (x *BatchInsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BatchInsertRequest) GetItems() []*BatchInsertItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      uint64                 `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertResponse) Reset() {
	*x = BatchInsertResponse{}
	mi := &file_databasa_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertResponse) ProtoMessage() {}

func (x *BatchInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasa_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertResponse.ProtoReflect.Descriptor instead.
func (*BatchInsertResponse) Descriptor() ([]byte, []int) {
	return file_databasa_proto_rawDescGZIP(), []int{22}
}

func (x *BatchInsertResponse) GetInserted() uint64 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

var File_databasa_proto protoreflect.FileDescriptor

const file_databasa_proto_rawDesc = "" +
	"\n" +
	"\x0edatabasa.proto\x12\bdatabasa\"u\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimension\x12(\n" +
	"\x06metric\x18\x03 \x01(\x0e2\x10.databasa.MetricR\x06metric\"\x1a\n" +
	"\x18CreateCollectionResponse\"-\n" +
	"\x17DeleteCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x18DeleteCollectionResponse\"\x9f\x01\n" +
	"\x0eCollectionInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimension\x12(\n" +
	"\x06metric\x18\x03 \x01(\x0e2\x10.databasa.MetricR\x06metric\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\x12\x1b\n" +
	"\thas_index\x18\x05 \x01(\bR\bhasIndex\"\x18\n" +
	"\x16ListCollectionsRequest\"U\n" +
	"\x17ListCollectionsResponse\x12:\n" +
	"\vcollections\x18\x01 \x03(\v2\x18.databasa.CollectionInfoR\vcollections\"k\n" +
	"\x12CreateIndexRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\f\n" +
	"\x01m\x18\x02 \x01(\rR\x01m\x12'\n" +
	"\x0fef_construction\x18\x03 \x01(\rR\x0eefConstruction\"\x15\n" +
	"\x13CreateIndexResponse\"2\n" +
	"\x10DropIndexRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"\x13\n" +
	"\x11DropIndexResponse\"_\n" +
	"\rInsertRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\"\x10\n" +
	"\x0eInsertResponse\">\n" +
	"\n" +
	"GetRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"=\n" +
	"\vGetResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\"A\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"\xac\x01\n" +
	"\rSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x12\x1b\n" +
	"\tef_search\x18\x04 \x01(\rR\befSearch\x12+\n" +
	"\x11include_embedding\x18\x05 \x01(\bR\x10includeEmbedding\"T\n" +
	"\fSearchResult\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\"B\n" +
	"\x0eSearchResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.databasa.SearchResultR\aresults\"A\n" +
	"\x0fBatchInsertItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\"e\n" +
	"\x12BatchInsertRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.databasa.BatchInsertItemR\x05items\"1\n" +
	"\x13BatchInsertResponse\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x04R\binserted*-\n" +
	"\x06Metric\x12\n" +
	"\n" +
	"\x06COSINE\x10\x00\x12\x06\n" +
	"\x02L2\x10\x01\x12\x0f\n" +
	"\vDOT_PRODUCT\x10\x022\xe1\x05\n" +
	"\bDatabasa\x12Y\n" +
	"\x10CreateCollection\x12!.databasa.CreateCollectionRequest\x1a\".databasa.CreateCollectionResponse\x12Y\n" +
	"\x10DeleteCollection\x12!.databasa.DeleteCollectionRequest\x1a\".databasa.DeleteCollectionResponse\x12V\n" +
	"\x0fListCollections\x12 .databasa.ListCollectionsRequest\x1a!.databasa.ListCollectionsResponse\x12J\n" +
	"\vCreateIndex\x12\x1c.databasa.CreateIndexRequest\x1a\x1d.databasa.CreateIndexResponse\x12D\n" +
	"\tDropIndex\x12\x1a.databasa.DropIndexRequest\x1a\x1b.databasa.DropIndexResponse\x12;\n" +
	"\x06Insert\x12\x17.databasa.InsertRequest\x1a\x18.databasa.InsertResponse\x122\n" +
	"\x03Get\x12\x14.databasa.GetRequest\x1a\x15.databasa.GetResponse\x12;\n" +
	"\x06Delete\x12\x17.databasa.DeleteRequest\x1a\x18.databasa.DeleteResponse\x12J\n" +
	"\vBatchInsert\x12\x1c.databasa.BatchInsertRequest\x1a\x1d.databasa.BatchInsertResponse\x12;\n" +
	"\x06Search\x12\x17.databasa.SearchRequest\x1a\x18.databasa.SearchResponseB$Z\"github.com/futlize/databasa/pkg/pbb\x06proto3"

var (
	file_databasa_proto_rawDescOnce sync.Once
	file_databasa_proto_rawDescData []byte
)

func file_databasa_proto_rawDescGZIP() []byte {
	file_databasa_proto_rawDescOnce.Do(func() {
		file_databasa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_databasa_proto_rawDesc), len(file_databasa_proto_rawDesc)))
	})
	return file_databasa_proto_rawDescData
}

var file_databasa_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_databasa_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_databasa_proto_goTypes = []any{
	(Metric)(0),                      // 0: databasa.Metric
	(*CreateCollectionRequest)(nil),  // 1: databasa.CreateCollectionRequest
	(*CreateCollectionResponse)(nil), // 2: databasa.CreateCollectionResponse
	(*DeleteCollectionRequest)(nil),  // 3: databasa.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil), // 4: databasa.DeleteCollectionResponse
	(*CollectionInfo)(nil),           // 5: databasa.CollectionInfo
	(*ListCollectionsRequest)(nil),   // 6: databasa.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),  // 7: databasa.ListCollectionsResponse
	(*CreateIndexRequest)(nil),       // 8: databasa.CreateIndexRequest
	(*CreateIndexResponse)(nil),      // 9: databasa.CreateIndexResponse
	(*DropIndexRequest)(nil),         // 10: databasa.DropIndexRequest
	(*DropIndexResponse)(nil),        // 11: databasa.DropIndexResponse
	(*InsertRequest)(nil),            // 12: databasa.InsertRequest
	(*InsertResponse)(nil),           // 13: databasa.InsertResponse
	(*GetRequest)(nil),               // 14: databasa.GetRequest
	(*GetResponse)(nil),              // 15: databasa.GetResponse
	(*DeleteRequest)(nil),            // 16: databasa.DeleteRequest
	(*DeleteResponse)(nil),           // 17: databasa.DeleteResponse
	(*SearchRequest)(nil),            // 18: databasa.SearchRequest
	(*SearchResult)(nil),             // 19: databasa.SearchResult
	(*SearchResponse)(nil),           // 20: databasa.SearchResponse
	(*BatchInsertItem)(nil),          // 21: databasa.BatchInsertItem
	(*BatchInsertRequest)(nil),       // 22: databasa.BatchInsertRequest
	(*BatchInsertResponse)(nil),      // 23: databasa.BatchInsertResponse
}
var file_databasa_proto_depIdxs = []int32{
	0,  // 0: databasa.CreateCollectionRequest.metric:type_name -> databasa.Metric
	0,  // 1: databasa.CollectionInfo.metric:type_name -> databasa.Metric
	5,  // 2: databasa.ListCollectionsResponse.collections:type_name -> databasa.CollectionInfo
	19, // 3: databasa.SearchResponse.results:type_name -> databasa.SearchResult
	21, // 4: databasa.BatchInsertRequest.items:type_name -> databasa.BatchInsertItem
	1,  // 5: databasa.Databasa.CreateCollection:input_type -> databasa.CreateCollectionRequest
	3,  // 6: databasa.Databasa.DeleteCollection:input_type -> databasa.DeleteCollectionRequest
	6,  // 7: databasa.Databasa.ListCollections:input_type -> databasa.ListCollectionsRequest
	8,  // 8: databasa.Databasa.CreateIndex:input_type -> databasa.CreateIndexRequest
	10, // 9: databasa.Databasa.DropIndex:input_type -> databasa.DropIndexRequest
	12, // 10: databasa.Databasa.Insert:input_type -> databasa.InsertRequest
	14, // 11: databasa.Databasa.Get:input_type -> databasa.GetRequest
	16, // 12: databasa.Databasa.Delete:input_type -> databasa.DeleteRequest
	22, // 13: databasa.Databasa.BatchInsert:input_type -> databasa.BatchInsertRequest
	18, // 14: databasa.Databasa.Search:input_type -> databasa.SearchRequest
	2,  // 15: databasa.Databasa.CreateCollection:output_type -> databasa.CreateCollectionResponse
	4,  // 16: databasa.Databasa.DeleteCollection:output_type -> databasa.DeleteCollectionResponse
	7,  // 17: databasa.Databasa.ListCollections:output_type -> databasa.ListCollectionsResponse
	9,  // 18: databasa.Databasa.CreateIndex:output_type -> databasa.CreateIndexResponse
	11, // 19: databasa.Databasa.DropIndex:output_type -> databasa.DropIndexResponse
	13, // 20: databasa.Databasa.Insert:output_type -> databasa.InsertResponse
	15, // 21: databasa.Databasa.Get:output_type -> databasa.GetResponse
	17, // 22: databasa.Databasa.Delete:output_type -> databasa.DeleteResponse
	23, // 23: databasa.Databasa.BatchInsert:output_type -> databasa.BatchInsertResponse
	20, // 24: databasa.Databasa.Search:output_type -> databasa.SearchResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_databasa_proto_init() }
func file_databasa_proto_init() {
	if File_databasa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_databasa_proto_rawDesc), len(file_databasa_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_databasa_proto_goTypes,
		DependencyIndexes: file_databasa_proto_depIdxs,
		EnumInfos:         file_databasa_proto_enumTypes,
		MessageInfos:      file_databasa_proto_msgTypes,
	}.Build()
	File_databasa_proto = out.File
	file_databasa_proto_goTypes = nil
	file_databasa_proto_depIdxs = nil
}
